### ISSUE TITLE
Are you sure this fails with strict unmarshalling? That could be a breaking change. I suspect some may have constructs ala:

### ISSUE THREAD

**Issue by devkadirselcuk** [gohugoio/hugo-mod-bootstrap-scss-v4#4]
Are you sure this fails with strict unmarshalling? That could be a breaking change. I suspect some may have constructs ala:

```
{{ range .Params.workson }}
{{ end }}
```

_Originally posted by @bep in https://github.com/gohugoio/hugo/pull/8428#discussion_r616896370_

**Comment by bep** [comment]
I appreciate issues, but I'm not a fan of cryptic issues of this type. Please open another with a more clear message.
